fix rlf-35 picture & update README
nevermore3d/Nevermore_Micro pull request #24
Opened 2023-01-25 16:55 UTC by docgalaxyblock

- [fix: rlf-35 mod pictures](https://github.com/nevermore3d/Nevermore_Micro/commit/15be6422739101f7a6f41fe99e7c0c3d0caad33e)
- [update README:](https://github.com/nevermore3d/Nevermore_Micro/commit/7d83c2d0c7d16d609d68bf32b2176ab90200e460)
  - add Delta BFB0524HH official links
  - remove VonWange (shop is closing)
  - minor cosmetic changes
  
I am not sure if [this](https://github.com/nevermore3d/Nevermore_Micro/compare/master...docgalaxyblock:Nevermore_Micro:master?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R167) is a bad idea since you can miss the acid-free-carbion section if you click on it.
I am open for feedback

👋

2023-04-10 21:28 UTC, 0ndsk4 approved these changes

2023-04-10 23:15 UTC, eduncan911 requested changes
Need to fix TOC

2023-04-10 23:15 UTC, eduncan911 commented on V5_Duo/Mods/RLF-35_by_Rama/Readme.md
> +![](img/11.jpg)
thanks for these

2023-04-10 23:15 UTC, eduncan911 commented on README.md
> +## BOM
You totally forgot to update the TOC.  I use a Codium plugin that handles my Markdown TOC.

Please either reverse these H2/H3 changes, or update the TOC to precisely match.

2023-04-11 09:43 UTC, docgalaxyblock commented on README.md
> +## BOM
Since I totally forgot this PR draft I am not sure what my intention was.
I guess I added the H2 bom cause of the link above that I think is questionable. Cause the `#bom` would be empty I did not added it to the TOC.


My initial question is still unanswered
> I am not sure if [**THIS**](https://github.com/nevermore3d/Nevermore_Micro/compare/master...docgalaxyblock:Nevermore_Micro:master?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R167) is a bad idea since you can miss the acid-free-carbion section if you click on it.

If I revert this I probably would revert the H2/H3 changes too since they have no real purpose anymore.
If I leave it in I personally see no benefit in adding it to the TOC

2023-04-11 14:09 UTC, eduncan911 commented on README.md
> +## BOM
The TOC is made up of the # headers.  It's not a question of rather it belongs in the TOC or not; but, rather the direct #, ##, ### headers you use.

If it doesn't belong in the TOC, then don't use # header prefixes.  :)

2023-04-11 21:41 UTC, docgalaxyblock commented on README.md
> +## BOM
That also does not answer my question 😂😅

Should [**this**](https://github.com/nevermore3d/Nevermore_Micro/compare/master...docgalaxyblock:Nevermore_Micro:master?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R167) stay there or not ❓

2023-06-09 11:20 UTC, docgalaxyblock commented
Since my last question was not answered I removed stuff again.

2023-10-11 18:58 UTC, docgalaxyblock commented
@eduncan911 @eduncan911 Hey, can we please finally merge this?

2024-01-27 22:13 UTC, closed without merging